### ISSUE TITLE
[BUG] - The motorway gantries can't be turned off. 

### ISSUE THREAD

**Issue by JackAttack438** [gamesphere/redwood#21]
As stated in the title.

**Comment by OliPayne-Welfordshire** [comment]
I also get this issue. ![bitmoji](https://render.bitstrips.com/v2/cpanel/ba97c72a-724b-440e-b242-f6155564afcc-69b909ed-a935-4ff6-bdeb-d939e2d16896-v1.png?transparent=1&palette=1&width=246)
