### ISSUE TITLE
[SUGGESTION] Temp Spawn with gun for FC

### ISSUE THREAD

**Issue by Dankskii** [gamesphere/redwood#4]
Firearms Team to spawn with a G36C Temp until xp is fixed

**Comment by dylanlegom** [comment]
A highways England control centre with cttv of motorway and  remote control to all the speed limits and led screens.

**Comment by dylanlegom** [comment]
A highways England control centre with cttv of motorway and remote control to all the speed limits and led screens. (More  realistic)

**Comment by YUS456** [comment]
Maybe try reducing lag for the lower end of the platforms
