### ISSUE TITLE
ELS still broken despite bug fix

### ISSUE THREAD

**Issue by Joepcro12** [gamesphere/redwood#53]
The ELS for LFB vehicles are still broken. It works for a bit but after a few minutes, a couple of the features disappear. 
![image](https://user-images.githubusercontent.com/36050148/57983777-8b522e00-7a4d-11e9-805b-d5b826ac24ea.png)

**Comment by Itsrobby-iiTrain** [comment]
It’s all the cars not just the fire service cars
